contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'EN'
weight = 1

title = 'Wildersense'
copyright = 'All Rights Reserved'

[author]
    name = "Jerry Papousek"
    description = ""
    email = "papousekj@protonmail.com"
